function [statistic_structure]=generate_statistic_structure();
%构造统计参数的结构体

statistic_structure=struct(...
    'xlable','SNR[dB]',...
    'ylable','Probability of error',...
    'x',[],...%每行x，对应一个图
    'y',[],...
    'legend','');